controllersClient:
    resource:
        path: ../src/Client/Controller/
        namespace: App\Client\Controller
    type: attribute
controllersCredit:
    resource:
        path: ../src/Credit/Controller/
        namespace: App\Credit\Controller
    type: attribute

